# Generated by Django 4.2.8 on 2024-01-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('afat', '0023_the_big_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatPaybackSetup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('time_to_look_back', models.IntegerField(default=30)),
                ('active_threshold', models.IntegerField(default=15)),
                ('value_from_moon_mining', models.BooleanField(default=True)),
                ('percentage_of_moon_mininig', models.FloatField(default=0.1)),
                ('alliances', models.ManyToManyField(
                    blank=True, to='eveonline.eveallianceinfo')),
                ('types_in_active', models.ManyToManyField(blank=True,
                 related_name='payback_types', to='afat.fleettype')),
            ],
        ),
    ]
