# Generated by Django 4.2.8 on 2024-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatpaybacks', '0002_fatpaybackrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatpaybackrecord',
            name='isk_per_active',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='fatpaybackrecord',
            name='total_actives',
            field=models.IntegerField(default=0),
        ),
    ]
